server:
  port: 8080
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-service
          uri: lb://user-service
          predicates:
            - Path=/exchangerate/**

  
 
