server:
 port: 8080

spring:
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true
   routes:
    - id: api-service
      uri: lb://api-service
      predicates:
       - Path=/exchangerate/**

  
 
