server:
 port: 8080 

spring:
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true
    routes:
     - id: api-service
       uri: http://localhost:8080/gbm/api/v1/apireto
       predicates:
        - Path=/exchangerate/**

  
 
