version: '3'

services:
 postgres9:
  image: postgres:9.6.12
  container_name: database_postgres
  volumes:
   - data:/opt/bd_apiok/data
  ports:
   - 5432:5432
  environment:
   POSTGRES_DB: bd_apiok
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres

volumes:
 data: {}